fix(project): add type definitions for prepend and prependTo
bpmn-io/tiny-svg pull request #9
Opened 2022-03-07 10:13 UTC by aljazerzen

I've noticed that type definitions do not contain `prepend` and `prependTo`. 

I hope I got formatting & commit message right.

2022-03-07 10:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bpmn-io/tiny-svg?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bpmn-io/tiny-svg?pullRequest=9) before we can accept your contribution.<br/><hr/>**aljazerzen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bpmn-io/tiny-svg?pullRequest=9) it.</sub>

2022-03-09 08:52 UTC, nikku commented on lib/index.d.ts
> + export function prepend(element: Element, node: SVGElement): typeof element;
```suggestion
export function prepend(element: Element, node: SVGElement): typeof element;
```

2022-03-09 08:52 UTC, nikku commented on lib/index.d.ts
> + export function prependTo(element: Element, target: SVGElement): typeof element;
```suggestion
export function prependTo(element: Element, target: SVGElement): typeof element;
```

2022-03-09 08:52 UTC, nikku requested changes
Great adjustment!

2022-03-09 11:20 UTC, aljazerzen commented on lib/index.d.ts
> + export function prependTo(element: Element, target: SVGElement): typeof element;
Whoops...

2022-03-09 12:34 UTC, merged

2022-03-09 12:34 UTC, nikku commented
Good job. Thanks!

2022-03-09 12:46 UTC, nikku commented
Released with `v2.2.3`.